import requests
from bs4 import BeautifulSoup
import io
import sys

#sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def parse_html(year):
#     url = "file://./qschina.cn_en_2023.html"
#     response = requests.get(url)
#     soup = BeautifulSoup(response.text, 'html.parser')

    text = ''
    path = './qschina.cn_en_%d.html'%(year)
    with open(path, 'r', encoding='utf-8') as file:
        text = file.read()
    soup = BeautifulSoup(text, 'html.parser')
    soup.prettify()

    ranking_data = []
    table = soup.find('table')
    if table:
        rows = table.find_all('tr')[1:]  #
        for row in rows:
            cols = row.find_all('td')
            if len(cols) >= 2:
                ranking_info = {
                    "rank": cols[0].text.strip(),
                    "university": cols[1].find('a').text.strip(),
#                     "country": cols[1].find('a').text.strip(),
#                     "total_score": cols[3].text.strip(),
#                     "country_rank": cols[4].text.strip()
                }
                print(ranking_info['university'])
                ranking_data.append(ranking_info)
    return ranking_data

year = 2022
year = 2023
# year = 2024
rankings = parse_html(year)
writeFilepath = '../resources/qs/qschina.cn_en_%d.data.txt'%(year)
with open(writeFilepath, 'w', encoding='utf-8') as file:
    file.write('# do not modify, auto-generated by python script')
    file.write("\n")
    for ranking in rankings:
    #     print(ranking)
        print(ranking['rank'])
        print(ranking['university'])

        file.write(ranking['rank'])
        file.write("\n")
        file.write(ranking['university'])
        file.write("\n")
